### ISSUE TITLE
Append selected columns from the original data to the result of dscore()

### ISSUE THREAD

**Issue by stefvanbuuren** [D-score/dscore#46]
The `dscore()` function returns the same number of rows in the same sequence as the input argument `data`. 

A user requested to append selected columns from the input data to the result of the `dscore()` function. These additional columns are useful in preserving ID and prevent merging errors in cases where the user sends a subset of rows from a larger data, e.g. as in `dscore(data[idx, ], ...)`.

**Comment by jmseiden** [comment]
We just got another request for this feature. One potential issue is that d-score output names (e.g. `d`, `sem`) could conflict with `data` names when appending selected columns. We will need to return an error if `data` contains an output name. Another alternative would be to require a unique `ID` in the package and then return `ID` (and `a`) along with scores.

**Comment by stefvanbuuren** [comment]
I propose to limit to a single column from `data`. This evades potential difficulties signaled by @jmseiden. 

The added ID-variable will have the same name in the result as in `data`. The name is assumed to differ from `a`, `d`, `sem` and the like. The values in the relevant column from `data` are copied into the output. If no values are found (e.g. because the column name was mis-specified), then all values in the output will be `NA_character`.

Note that if the user wants to merge the result with the original based on the requested ID-variable, it is the user's responsibility that ID contains unique values suitable for merging.

**Comment by stefvanbuuren** [comment]
`dscore 1.8.5` introduces the `prepend` argument the `dscore()` and `dscore_posterior()` functions. This allows the user to copy over one or more columns into the returned data frame. The copied columns will be placed before the results calculated by `dscore()` and `dscore_posterior()`, and the argument is called `prepend` to reflect this.

Handling of name clashes: 
- If a name specified in `prepend` equals one produced by `dscore()` or `dscore_posterior()` (e.g. `n`, `d`, `sem`), the function throws an "overwrite" warning, and prioritizes the newly calculated results;
- If a name specified in `prepend` is not found in `data`, then the function throws a warning and does not create the column.

Examples: 

``` r
library(dscore)  # >= 1.8.5

data <- data.frame(
  id = c("Jane", "Martin", "ID-3", "No. 4", "Five", "6",
         NA_character_, as.character(8:10)),
  age = rep(round(21 / 365.25, 4), 10),
  ddifmd001 = c(NA, NA, 0, 0, 0, 1, 0, 1, 1, 1),
  ddicmm029 = c(NA, NA, NA, 0, 1, 0, 1, 0, 1, 1),
  ddigmd053 = c(NA, 0, 0, 1, 0, 0, 1, 1, 0, 1)
)

# prepend the id column to the result
head(dscore(data, prepend = "id"), 4)
#>       id      a n  p    d      sem    daz
#> 1   Jane     NA 0 NA   NA       NA     NA
#> 2 Martin     NA 0 NA   NA       NA     NA
#> 3   ID-3 0.0575 1  0 6.61 2.763004 -2.019
#> 4  No. 4 0.0575 2  0 5.60 2.459750 -2.235

# if you're lazy, prepend all
head(dscore(data, prepend = colnames(data)), 4)
#>       id    age ddifmd001 ddicmm029 ddigmd053      a n  p    d      sem    daz
#> 1   Jane 0.0575        NA        NA        NA     NA 0 NA   NA       NA     NA
#> 2 Martin 0.0575        NA        NA         0     NA 0 NA   NA       NA     NA
#> 3   ID-3 0.0575         0        NA         0 0.0575 1  0 6.61 2.763004 -2.019
#> 4  No. 4 0.0575         0         0         1 0.0575 2  0 5.60 2.459750 -2.235
```

<sup>Created on 2024-03-29 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
